In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
dataset = pd.read_csv("AIML.csv")

In [48]:
dataset

   Gender  CLIENTNUM  Customer_Age  Months_on_book  Total_Relationship_Count
0       M  768805383            45              39                         5
1       F  818770008            49              44                         6
2       M  713982108            51              36                         4
3       F  769911858            40              34                         3
4       M  709106358            40              21                         5
..    ...        ...           ...             ...                       ...
94      F  715550508            45              28                         5
95      M  719712633            64              52                         6
96      M  772629333            45              35                         5
97      M  720336708            53              35                         5
98      M  802013583            56              50                         3

[99 rows x 5 columns]

In [49]:
dataset.isnull()

    Gender  CLIENTNUM  Customer_Age  Months_on_book  Total_Relationship_Count
0    False      False         False           False                     False
1    False      False         False           False                     False
2    False      False         False           False                     False
3    False      False         False           False                     False
4    False      False         False           False                     False
..     ...        ...           ...             ...                       ...
94   False      False         False           False                     False
95   False      False         False           False                     False
96   False      False         False           False                     False
97   False      False         False           False                     False
98   False      False         False           False                     False

[99 rows x 5 columns]

In [50]:
dataset.isnull().sum()

Gender                      0
CLIENTNUM                   0
Customer_Age                0
Months_on_book              0
Total_Relationship_Count    0
dtype: int64

In [51]:
x=dataset.iloc[:,0:3].values
y=dataset.iloc[:,3:4].values

In [52]:
x.shape

(99, 3)

In [53]:
y.shape

(99, 1)

In [54]:
x

array([['M', 768805383, 45],
       ['F', 818770008, 49],
       ['M', 713982108, 51],
       ['F', 769911858, 40],
       ['M', 709106358, 40],
       ['M', 713061558, 44],
       ['M', 810347208, 51],
       ['M', 818906208, 32],
       ['M', 710930508, 37],
       ['M', 719661558, 48],
       ['M', 708790833, 42],
       ['M', 710821833, 65],
       ['M', 710599683, 56],
       ['M', 816082233, 35],
       ['F', 712396908, 57],
       ['M', 714885258, 44],
       ['M', 709967358, 48],
       ['M', 753327333, 41],
       ['M', 806160108, 61],
       ['F', 709327383, 45],
       ['M', 806165208, 47],
       ['F', 708508758, 62],
       ['M', 784725333, 41],
       ['F', 811604133, 47],
       ['M', 789124683, 54],
       ['F', 771071958, 41],
       ['M', 720466383, 59],
       ['M', 804424383, 63],
       ['F', 718813833, 44],
       ['M', 806624208, 47],
       ['M', 778348233, 53],
       ['M', 712991808, 53],
       ['M', 709029408, 41],
       ['F', 788658483, 53],
       ['M', 787937058, 58],
       ['F', 715318008, 55],
       ['F', 713962233, 55],
       ['F', 785432733, 42],
       ['F', 715190283, 57],
       ['F', 708300483, 66],
       ['M', 827111283, 45],
       ['M', 758551608, 51],
       ['F', 773146383, 50],
       ['M', 778493808, 49],
       ['F', 720572508, 38],
       ['M', 712661433, 49],
       ['M', 789172683, 56],
       ['M', 738406533, 59],
       ['M', 799723908, 46],
       ['M', 771490833, 52],
       ['F', 720756708, 52],
       ['F', 779471883, 54],
       ['F', 711525033, 66],
       ['M', 712813458, 49],
       ['M', 714374133, 56],
       ['F', 717891558, 49],
       ['F', 716632758, 49],
       ['M', 768563658, 56],
       ['F', 711427458, 44],
       ['M', 714091983, 42],
       ['M', 787584108, 55],
       ['M', 712030833, 48],
       ['M', 711481533, 39],
       ['M', 710082708, 44],
       ['M', 708155733, 53],
       ['M', 788979258, 51],
       ['M', 807986133, 57],
       ['F', 788730933, 44],
       ['M', 711314058, 49],
       ['M', 717975333, 50],
       ['M', 715971108, 51],
       ['F', 720096558, 55],
       ['M', 719580033, 54],
       ['M', 820582308, 42],
       ['M', 789973308, 44],
       ['M', 712876233, 53],
       ['F', 804595158, 44],
       ['F', 714826758, 37],
       ['M', 779058108, 49],
       ['M', 710790258, 47],
       ['M', 715623483, 47],
       ['M', 715156383, 44],
       ['F', 711013983, 55],
       ['F', 755420433, 59],
       ['M', 794543958, 53],
       ['M', 716396358, 52],
       ['M', 715398033, 53],
       ['F', 711743883, 43],
       ['M', 719720058, 44],
       ['M', 778992108, 57],
       ['F', 717539808, 51],
       ['M', 714070758, 49],
       ['M', 714107958, 45],
       ['M', 789140283, 53],
       ['F', 715550508, 45],
       ['M', 719712633, 64],
       ['M', 772629333, 45],
       ['M', 720336708, 53],
       ['M', 802013583, 56]], dtype=object)

In [55]:
y

array([[39],
       [44],
       [36],
       [34],
       [21],
       [36],
       [46],
       [27],
       [36],
       [36],
       [31],
       [54],
       [36],
       [30],
       [48],
       [37],
       [36],
       [34],
       [56],
       [37],
       [42],
       [49],
       [33],
       [36],
       [42],
       [28],
       [46],
       [56],
       [34],
       [42],
       [33],
       [48],
       [36],
       [38],
       [49],
       [36],
       [36],
       [36],
       [49],
       [56],
       [41],
       [44],
       [43],
       [37],
       [28],
       [30],
       [45],
       [52],
       [40],
       [40],
       [41],
       [40],
       [54],
       [36],
       [36],
       [36],
       [36],
       [50],
       [35],
       [34],
       [47],
       [35],
       [33],
       [32],
       [44],
       [38],
       [52],
       [20],
       [32],
       [38],
       [42],
       [42],
       [43],
       [37],
       [35],
       [36],
       [36],
       [29],
       [30],
       [38],
       [37],
       [36],
       [45],
       [52],
       [35],
       [47],
       [35],
       [35],
       [31],
       [45],
       [36],
       [38],
       [36],
       [42],
       [28],
       [52],
       [35],
       [35],
       [50]])

In [56]:
from sklearn.preprocessing import LabelEncoder 
Label_x = LabelEncoder()
x[:,0]= Label_x.fit_transform(x[:,0])

In [57]:
x

array([[1, 768805383, 45],
       [0, 818770008, 49],
       [1, 713982108, 51],
       [0, 769911858, 40],
       [1, 709106358, 40],
       [1, 713061558, 44],
       [1, 810347208, 51],
       [1, 818906208, 32],
       [1, 710930508, 37],
       [1, 719661558, 48],
       [1, 708790833, 42],
       [1, 710821833, 65],
       [1, 710599683, 56],
       [1, 816082233, 35],
       [0, 712396908, 57],
       [1, 714885258, 44],
       [1, 709967358, 48],
       [1, 753327333, 41],
       [1, 806160108, 61],
       [0, 709327383, 45],
       [1, 806165208, 47],
       [0, 708508758, 62],
       [1, 784725333, 41],
       [0, 811604133, 47],
       [1, 789124683, 54],
       [0, 771071958, 41],
       [1, 720466383, 59],
       [1, 804424383, 63],
       [0, 718813833, 44],
       [1, 806624208, 47],
       [1, 778348233, 53],
       [1, 712991808, 53],
       [1, 709029408, 41],
       [0, 788658483, 53],
       [1, 787937058, 58],
       [0, 715318008, 55],
       [0, 713962233, 55],
       [0, 785432733, 42],
       [0, 715190283, 57],
       [0, 708300483, 66],
       [1, 827111283, 45],
       [1, 758551608, 51],
       [0, 773146383, 50],
       [1, 778493808, 49],
       [0, 720572508, 38],
       [1, 712661433, 49],
       [1, 789172683, 56],
       [1, 738406533, 59],
       [1, 799723908, 46],
       [1, 771490833, 52],
       [0, 720756708, 52],
       [0, 779471883, 54],
       [0, 711525033, 66],
       [1, 712813458, 49],
       [1, 714374133, 56],
       [0, 717891558, 49],
       [0, 716632758, 49],
       [1, 768563658, 56],
       [0, 711427458, 44],
       [1, 714091983, 42],
       [1, 787584108, 55],
       [1, 712030833, 48],
       [1, 711481533, 39],
       [1, 710082708, 44],
       [1, 708155733, 53],
       [1, 788979258, 51],
       [1, 807986133, 57],
       [0, 788730933, 44],
       [1, 711314058, 49],
       [1, 717975333, 50],
       [1, 715971108, 51],
       [0, 720096558, 55],
       [1, 719580033, 54],
       [1, 820582308, 42],
       [1, 789973308, 44],
       [1, 712876233, 53],
       [0, 804595158, 44],
       [0, 714826758, 37],
       [1, 779058108, 49],
       [1, 710790258, 47],
       [1, 715623483, 47],
       [1, 715156383, 44],
       [0, 711013983, 55],
       [0, 755420433, 59],
       [1, 794543958, 53],
       [1, 716396358, 52],
       [1, 715398033, 53],
       [0, 711743883, 43],
       [1, 719720058, 44],
       [1, 778992108, 57],
       [0, 717539808, 51],
       [1, 714070758, 49],
       [1, 714107958, 45],
       [1, 789140283, 53],
       [0, 715550508, 45],
       [1, 719712633, 64],
       [1, 772629333, 45],
       [1, 720336708, 53],
       [1, 802013583, 56]], dtype=object)

In [58]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 
from sklearn.compose import ColumnTransformer
Label_x = LabelEncoder()
x[:,0]= Label_x.fit_transform(x[:,0])
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(), [0])], 
    remainder='passthrough'
)

x = np.array(ct.fit_transform(x), dtype=np.int)

Label_y= LabelEncoder() 
y=Label_y.fit_transform(y)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [59]:
x=x[:,1:]

In [60]:
x

array([[        1, 768805383,        45],
       [        0, 818770008,        49],
       [        1, 713982108,        51],
       [        0, 769911858,        40],
       [        1, 709106358,        40],
       [        1, 713061558,        44],
       [        1, 810347208,        51],
       [        1, 818906208,        32],
       [        1, 710930508,        37],
       [        1, 719661558,        48],
       [        1, 708790833,        42],
       [        1, 710821833,        65],
       [        1, 710599683,        56],
       [        1, 816082233,        35],
       [        0, 712396908,        57],
       [        1, 714885258,        44],
       [        1, 709967358,        48],
       [        1, 753327333,        41],
       [        1, 806160108,        61],
       [        0, 709327383,        45],
       [        1, 806165208,        47],
       [        0, 708508758,        62],
       [        1, 784725333,        41],
       [        0, 811604133,        47],
       [        1, 789124683,        54],
       [        0, 771071958,        41],
       [        1, 720466383,        59],
       [        1, 804424383,        63],
       [        0, 718813833,        44],
       [        1, 806624208,        47],
       [        1, 778348233,        53],
       [        1, 712991808,        53],
       [        1, 709029408,        41],
       [        0, 788658483,        53],
       [        1, 787937058,        58],
       [        0, 715318008,        55],
       [        0, 713962233,        55],
       [        0, 785432733,        42],
       [        0, 715190283,        57],
       [        0, 708300483,        66],
       [        1, 827111283,        45],
       [        1, 758551608,        51],
       [        0, 773146383,        50],
       [        1, 778493808,        49],
       [        0, 720572508,        38],
       [        1, 712661433,        49],
       [        1, 789172683,        56],
       [        1, 738406533,        59],
       [        1, 799723908,        46],
       [        1, 771490833,        52],
       [        0, 720756708,        52],
       [        0, 779471883,        54],
       [        0, 711525033,        66],
       [        1, 712813458,        49],
       [        1, 714374133,        56],
       [        0, 717891558,        49],
       [        0, 716632758,        49],
       [        1, 768563658,        56],
       [        0, 711427458,        44],
       [        1, 714091983,        42],
       [        1, 787584108,        55],
       [        1, 712030833,        48],
       [        1, 711481533,        39],
       [        1, 710082708,        44],
       [        1, 708155733,        53],
       [        1, 788979258,        51],
       [        1, 807986133,        57],
       [        0, 788730933,        44],
       [        1, 711314058,        49],
       [        1, 717975333,        50],
       [        1, 715971108,        51],
       [        0, 720096558,        55],
       [        1, 719580033,        54],
       [        1, 820582308,        42],
       [        1, 789973308,        44],
       [        1, 712876233,        53],
       [        0, 804595158,        44],
       [        0, 714826758,        37],
       [        1, 779058108,        49],
       [        1, 710790258,        47],
       [        1, 715623483,        47],
       [        1, 715156383,        44],
       [        0, 711013983,        55],
       [        0, 755420433,        59],
       [        1, 794543958,        53],
       [        1, 716396358,        52],
       [        1, 715398033,        53],
       [        0, 711743883,        43],
       [        1, 719720058,        44],
       [        1, 778992108,        57],
       [        0, 717539808,        51],
       [        1, 714070758,        49],
       [        1, 714107958,        45],
       [        1, 789140283,        53],
       [        0, 715550508,        45],
       [        1, 719712633,        64],
       [        1, 772629333,        45],
       [        1, 720336708,        53],
       [        1, 802013583,        56]])

In [61]:
y

array([14, 19, 11,  9,  1, 11, 21,  2, 11, 11,  6, 27, 11,  5, 23, 12, 11,
        9, 28, 12, 17, 24,  8, 11, 17,  3, 21, 28,  9, 17,  8, 23, 11, 13,
       24, 11, 11, 11, 24, 28, 16, 19, 18, 12,  3,  5, 20, 26, 15, 15, 16,
       15, 27, 11, 11, 11, 11, 25, 10,  9, 22, 10,  8,  7, 19, 13, 26,  0,
        7, 13, 17, 17, 18, 12, 10, 11, 11,  4,  5, 13, 12, 11, 20, 26, 10,
       22, 10, 10,  6, 20, 11, 13, 11, 17,  3, 26, 10, 10, 25])

In [62]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=.20, random_state = 0)

In [63]:
xtrain.shape

(79, 3)

In [64]:
ytrain.shape

(79,)

In [65]:
xtest.shape

(20, 3)

In [66]:
ytest.shape

(20,)

In [68]:
from sklearn.preprocessing import StandardScaler 
Sc_x = StandardScaler() 
xtrain=Sc_x.fit_transform(xtrain) 
xtest=Sc_x.transform(xtest)

In [69]:
xtrain

array([[ 0.74095857,  0.83044253, -0.1660396 ],
       [ 0.74095857, -0.90195015, -1.60748225],
       [-1.34960312,  0.60858306, -1.46333798],
       [-1.34960312, -0.67923564,  0.69882599],
       [ 0.74095857, -0.87144753, -0.1660396 ],
       [ 0.74095857,  1.37928033, -0.59847239],
       [ 0.74095857,  1.65391251,  0.12224893],
       [ 0.74095857,  1.43847271,  0.84297026],
       [-1.34960312, -0.91403719,  0.69882599],
       [-1.34960312,  1.50521125, -0.88676092],
       [ 0.74095857,  1.06544379,  0.69882599],
       [ 0.74095857, -0.79487299, -0.45432813],
       [ 0.74095857,  0.84332451,  0.98711452],
       [ 0.74095857, -0.90627969, -0.1660396 ],
       [-1.34960312,  0.85572759,  0.55468173],
       [ 0.74095857,  1.5007964 ,  1.85198011],
       [ 0.74095857,  1.54566814,  1.56369158],
       [-1.34960312, -0.76878135, -0.1660396 ],
       [ 0.74095857, -0.93811239, -0.88676092],
       [ 0.74095857,  1.12720908, -0.88676092],
       [-1.34960312,  1.87165764, -0.1660396 ],
       [ 0.74095857, -0.88774972, -0.31018386],
       [-1.34960312,  0.69220159, -0.02189533],
       [ 0.74095857,  0.31489935,  0.12224893],
       [ 0.74095857, -0.96335287, -1.46333798],
       [ 0.74095857, -0.81395749, -0.88676092],
       [ 0.74095857,  0.17984207, -1.31919372],
       [ 0.74095857,  2.08729521, -0.74261666],
       [-1.34960312, -0.80607202,  0.98711452],
       [ 0.74095857, -0.86110355, -0.88676092],
       [-1.34960312, -0.74533241,  0.12224893],
       [ 0.74095857, -0.83446513, -1.17504945],
       [ 0.74095857,  0.57997861, -0.74261666],
       [ 0.74095857,  1.0745682 ,  1.13125879],
       [-1.34960312, -0.71239648, -0.88676092],
       [-1.34960312, -0.66216952,  0.2663932 ],
       [ 0.74095857, -0.91900463,  2.14026864],
       [-1.34960312, -0.80277009,  0.69882599],
       [-1.34960312,  1.68640637, -0.45432813],
       [-1.34960312, -0.90082559,  2.28441291],
       [ 0.74095857, -0.97150978, -1.17504945],
       [ 0.74095857, -0.86290672,  0.41053746],
       [ 0.74095857,  1.5928743 ,  0.98711452],
       [ 0.74095857,  0.57372957,  0.84297026],
       [ 0.74095857, -0.9198209 , -0.45432813],
       [ 0.74095857, -0.77489273,  0.2663932 ],
       [ 0.74095857, -0.96534217, -1.31919372],
       [ 0.74095857,  1.24536893,  0.41053746],
       [-1.34960312, -0.87828599,  0.98711452],
       [ 0.74095857, -0.68896887, -0.88676092],
       [-1.34960312, -0.95763896, -0.74261666],
       [ 0.74095857,  1.55766599, -0.45432813],
       [ 0.74095857,  0.64940252,  0.2663932 ],
       [ 0.74095857,  0.67883488, -0.74261666],
       [ 0.74095857, -0.67302731,  0.41053746],
       [ 0.74095857, -0.73407327, -0.02189533],
       [ 0.74095857,  1.54579998, -0.45432813],
       [ 0.74095857,  1.10567382,  0.41053746],
       [ 0.74095857, -0.69258877,  0.55468173],
       [-1.34960312, -0.81546983, -1.89577078],
       [-1.34960312,  0.63857382, -1.31919372],
       [-1.34960312,  1.00982672, -1.17504945],
       [ 0.74095857, -0.8069484 , -0.88676092],
       [ 0.74095857,  1.10651142,  0.84297026],
       [-1.34960312, -0.98418624,  2.28441291],
       [ 0.74095857,  1.10151102,  0.12224893],
       [-1.34960312, -0.90334809, -0.88676092],
       [ 0.74095857, -0.92474762,  0.84297026],
       [ 0.74095857, -0.78588624,  0.12224893],
       [-1.34960312, -0.89516791, -1.03090519],
       [-1.34960312, -0.83781941,  0.69882599],
       [-1.34960312, -0.97880195,  1.70783585],
       [-1.34960312,  0.23395262,  1.27540305],
       [ 0.74095857, -0.6904812 , -0.31018386],
       [ 0.74095857, -0.68916082,  1.99612438],
       [-1.34960312,  1.09509136, -0.88676092],
       [ 0.74095857, -0.9879283 ,  0.41053746],
       [ 0.74095857, -0.20588853,  1.27540305],
       [-1.34960312, -0.66693144, -1.75162651]])

In [70]:
xtest

array([[ 0.74095857, -0.66967497,  1.27540305],
       [ 0.74095857, -0.8007013 ,  0.41053746],
       [ 0.74095857, -0.83730561,  0.12224893],
       [-1.34960312, -0.73623901, -0.1660396 ],
       [ 0.74095857, -0.86589455,  0.41053746],
       [ 0.74095857, -0.83405215, -0.74261666],
       [ 0.74095857, -0.94109441, -0.31018386],
       [ 0.74095857,  1.91850899, -1.17504945],
       [ 0.74095857, -0.82717103,  0.84297026],
       [-1.34960312, -0.79675953, -0.74261666],
       [ 0.74095857, -0.8675174 , -0.1660396 ],
       [ 0.74095857, -0.83501384, -0.1660396 ],
       [ 0.74095857,  0.84503074, -0.1660396 ],
       [ 0.74095857,  1.80217363, -2.18405931],
       [ 0.74095857,  1.87517867, -2.6164921 ],
       [ 0.74095857,  0.82667914,  0.41053746],
       [ 0.74095857,  0.9915391 , -1.31919372],
       [ 0.74095857,  1.10527053,  0.55468173],
       [-1.34960312,  1.09321839,  0.41053746],
       [ 0.74095857, -0.91619518, -1.89577078]])

In [71]:
ytest

array([21, 10, 11, 11, 11, 11, 11, 12, 11,  3, 11, 13,  5,  5,  2,  8,  8,
       17, 13, 11])

In [72]:
ytrain

array([12,  8,  9, 17,  5, 15, 21, 25, 20, 11, 22, 12, 20,  7, 15, 28, 28,
       11,  7, 10, 19, 10, 18, 19,  1, 12,  9, 16, 24, 11, 11,  9, 14, 24,
        9, 16, 27, 11, 11, 27,  6, 23, 26, 25, 13, 22, 11, 10, 23,  6, 12,
       17, 15, 10, 10, 13, 17, 17, 18,  4,  3, 11, 11, 20, 28, 13, 10, 11,
       17, 10, 11, 24, 26, 11, 26,  0, 19, 26,  3])